[uwsgi]
chdir = /mapproxy
wsgi-file = ${MAPPROXY_APP_DIR}/app.py
pidfile = /tmp/mapproxy.pid
http = 0.0.0.0:8080
processes = ${PROCESSES}
cheaper = ${CHEAPER}
enable-threads = true
threads = ${THREADS}
master = true
vacuum = true
die-on-term = true
need-app = true
max-requests = 1000
max-worker-lifetime = 3600
reload-on-rss = 2048
worker-reload-mercy = 60
disable-logging = ${DISABLE_LOGGING}
log-4xx = ${LOG4XX}
log-5xx = ${LOG5XX}
wsgi-disable-file-wrapper = true
memory-report = true
harakiri = 60
py-callos-afterfork = true
cheaper-algo = busyness
cheaper-initial = ${CHEAPER}
cheaper-overload = 1
cheaper-step = ${CHEAPER}
cheaper-busyness-multiplier = 30
cheaper-busyness-min = 20
cheaper-busyness-max = 70
cheaper-busyness-backlog-alert = ${CHEAPER}
cheaper-busyness-backlog-step = 2
